#!/usr/bin/env python3
"""
Hotel Management System - Database Migration Script
====================================================
migrate_monges.py

This script migrates the database to support:
- Dynamic property configuration
- Room categories (for Los Monges category-based model)
- Dynamic pricing (client types, seasons, contracts)
- Room status tracking

USAGE:
    python scripts/migrate_monges.py [--dry-run] [--no-backup]

FLAGS:
    --dry-run    Show what would be done without making changes
    --no-backup  Skip automatic backup (not recommended)

SAFETY:
    - Creates automatic backup before migration
    - Safe to run multiple times (checks if tables exist)
    - All operations are wrapped in transactions
    - Rollback on any error

Author: Generated by Claude Desktop
Date: 2026-01-31
Phase: Los Monges MVP
"""

import os
import sys
import shutil
import sqlite3
from datetime import datetime
from pathlib import Path

# ============================================
# CONFIGURATION
# ============================================

# Detect script location and project root
SCRIPT_DIR = Path(os.path.abspath(os.path.dirname(__file__)))
PROJECT_ROOT = SCRIPT_DIR.parent
BACKEND_DIR = PROJECT_ROOT / "backend"
DB_PATH = BACKEND_DIR / "hotel.db"
BACKUP_DIR = PROJECT_ROOT / "backups"

# Migration version (increment when adding new migrations)
MIGRATION_VERSION = "1.0.0"
MIGRATION_NAME = "los_monges_mvp"

# ============================================
# LOGGING (Simple console output)
# ============================================

def log_info(msg: str):
    print(f"[INFO] {msg}")

def log_success(msg: str):
    print(f"[✅] {msg}")

def log_warning(msg: str):
    print(f"[⚠️] {msg}")

def log_error(msg: str):
    print(f"[❌] {msg}")

def log_section(title: str):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}\n")

# ============================================
# BACKUP FUNCTIONS
# ============================================

def create_backup(db_path: Path, backup_dir: Path) -> Path:
    """Create a timestamped backup of the database."""
    backup_dir.mkdir(parents=True, exist_ok=True)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_name = f"hotel_pre_migration_{MIGRATION_NAME}_{timestamp}.db"
    backup_path = backup_dir / backup_name
    
    log_info(f"Creating backup: {backup_path}")
    
    # Use SQLite's backup API for safe copy
    source_conn = sqlite3.connect(str(db_path))
    backup_conn = sqlite3.connect(str(backup_path))
    
    source_conn.backup(backup_conn)
    
    backup_conn.close()
    source_conn.close()
    
    # Verify backup
    if backup_path.exists():
        size_mb = backup_path.stat().st_size / (1024 * 1024)
        log_success(f"Backup created: {backup_name} ({size_mb:.2f} MB)")
        return backup_path
    else:
        raise Exception("Backup creation failed!")

# ============================================
# MIGRATION: NEW TABLES
# ============================================

# SQL statements for new tables
SQL_CREATE_TABLES = """
-- ============================================
-- PROPERTY CONFIGURATION TABLES
-- ============================================

-- Properties (Hotels)
CREATE TABLE IF NOT EXISTS properties (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE,
    display_mode TEXT DEFAULT 'category' CHECK (display_mode IN ('numbered', 'category')),
    theme_background TEXT DEFAULT '#FFFFFF',
    theme_text TEXT DEFAULT '#000000',
    theme_primary TEXT DEFAULT '#1E3A5F',
    check_in_start TEXT DEFAULT '07:00',
    check_in_end TEXT DEFAULT '22:00',
    check_out_time TEXT DEFAULT '10:00',
    breakfast_included INTEGER DEFAULT 0,
    parking_available INTEGER DEFAULT 1,
    timezone TEXT DEFAULT 'America/Asuncion',
    currency TEXT DEFAULT 'PYG',
    address TEXT,
    phone TEXT,
    email TEXT,
    facebook_url TEXT,
    instagram_url TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    active INTEGER DEFAULT 1
);

-- iCal feeds for Booking.com/Airbnb sync per room
CREATE TABLE IF NOT EXISTS ical_feeds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    room_id TEXT NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
    source TEXT NOT NULL,
    ical_url TEXT NOT NULL,
    last_synced_at TIMESTAMP,
    sync_enabled INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Buildings within a property
CREATE TABLE IF NOT EXISTS buildings (
    id TEXT PRIMARY KEY,
    property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    name TEXT DEFAULT 'Principal',
    floors INTEGER DEFAULT 1,
    description TEXT,
    sort_order INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Room categories (templates with base pricing)
CREATE TABLE IF NOT EXISTS room_categories (
    id TEXT PRIMARY KEY,
    property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    base_price DECIMAL(12,2) NOT NULL,
    max_capacity INTEGER NOT NULL,
    bed_configuration TEXT,  -- JSON: [{"type": "matrimonial", "qty": 1}]
    amenities TEXT,          -- JSON: ["wifi", "ac", "tv"]
    image_url TEXT,
    sort_order INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- System settings per property
CREATE TABLE IF NOT EXISTS system_settings (
    id TEXT PRIMARY KEY,
    property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    setting_key TEXT NOT NULL,
    setting_value TEXT,
    setting_type TEXT DEFAULT 'string' CHECK (setting_type IN ('string', 'number', 'boolean', 'json')),
    description TEXT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by TEXT,
    UNIQUE(property_id, setting_key)
);

-- ============================================
-- ROOM MANAGEMENT TABLES
-- ============================================

-- Modified rooms table (if not exists, creates new; if exists, we'll alter it)
CREATE TABLE IF NOT EXISTS rooms_new (
    id TEXT PRIMARY KEY,
    property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    building_id TEXT REFERENCES buildings(id),
    category_id TEXT REFERENCES room_categories(id),
    floor INTEGER,
    room_number TEXT,
    internal_code TEXT,      -- Internal reference (e.g., "DF-01" for Dept Familiar 1)
    custom_price DECIMAL(12,2),    -- Override category price if set
    custom_capacity INTEGER,        -- Override category capacity if set
    custom_beds TEXT,               -- Override category beds if set (JSON)
    status TEXT DEFAULT 'available' CHECK (status IN ('available', 'occupied', 'maintenance', 'out_of_service', 'cleaning')),
    status_reason TEXT,
    status_changed_at TIMESTAMP,
    status_changed_by TEXT,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    active INTEGER DEFAULT 1
);

-- Room status change log (for reports and auditing)
CREATE TABLE IF NOT EXISTS room_status_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    room_id TEXT NOT NULL,
    property_id TEXT NOT NULL,
    old_status TEXT,
    new_status TEXT NOT NULL,
    reason TEXT,
    changed_by TEXT,
    changed_by_type TEXT DEFAULT 'user' CHECK (changed_by_type IN ('user', 'ai_agent', 'system', 'api')),
    changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- PRICING SYSTEM TABLES
-- ============================================

-- Client types with default discounts
CREATE TABLE IF NOT EXISTS client_types (
    id TEXT PRIMARY KEY,
    property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    default_discount_percent DECIMAL(5,2) DEFAULT 0,
    requires_contract INTEGER DEFAULT 0,
    min_rooms_per_booking INTEGER DEFAULT 1,
    color TEXT DEFAULT '#6B7280',  -- For UI display
    icon TEXT,                      -- Icon name for UI
    sort_order INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(property_id, name)
);

-- Company/Agency contracts with negotiated rates
CREATE TABLE IF NOT EXISTS client_contracts (
    id TEXT PRIMARY KEY,
    property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    client_type_id TEXT NOT NULL REFERENCES client_types(id),
    company_name TEXT NOT NULL,
    ruc TEXT,                       -- Tax ID (Paraguay: RUC)
    contact_name TEXT,
    contact_phone TEXT,
    contact_email TEXT,
    billing_address TEXT,
    negotiated_discount_percent DECIMAL(5,2) NOT NULL,
    credit_days INTEGER DEFAULT 0,  -- Payment terms (0 = immediate)
    credit_limit DECIMAL(12,2),     -- Maximum credit amount
    valid_from DATE,
    valid_until DATE,               -- NULL = no expiration
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    active INTEGER DEFAULT 1
);

-- Seasonal pricing rules
CREATE TABLE IF NOT EXISTS pricing_seasons (
    id TEXT PRIMARY KEY,
    property_id TEXT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    price_modifier DECIMAL(5,2) NOT NULL,  -- 1.25 = +25%, 0.85 = -15%
    applies_to_categories TEXT,             -- JSON array of category IDs, NULL = all
    priority INTEGER DEFAULT 0,             -- Higher = takes precedence
    color TEXT DEFAULT '#F59E0B',           -- For calendar display
    active INTEGER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(property_id, name, start_date, end_date)
);

-- Price calculation audit log
CREATE TABLE IF NOT EXISTS price_calculations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    reservation_id TEXT,
    property_id TEXT NOT NULL,
    category_id TEXT,
    category_name TEXT,
    base_price_per_night DECIMAL(12,2) NOT NULL,
    nights INTEGER NOT NULL,
    base_total DECIMAL(12,2) NOT NULL,
    client_type_id TEXT,
    client_type_name TEXT,
    client_type_modifier DECIMAL(5,2) DEFAULT 1.0,
    client_discount_amount DECIMAL(12,2) DEFAULT 0,
    contract_id TEXT,
    contract_name TEXT,
    season_id TEXT,
    season_name TEXT,
    season_modifier DECIMAL(5,2) DEFAULT 1.0,
    season_adjustment_amount DECIMAL(12,2) DEFAULT 0,
    special_discount_percent DECIMAL(5,2) DEFAULT 0,
    special_discount_reason TEXT,
    special_discount_amount DECIMAL(12,2) DEFAULT 0,
    final_price DECIMAL(12,2) NOT NULL,
    calculation_details TEXT,   -- Full JSON breakdown
    calculated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    calculated_by TEXT
);

-- ============================================
-- AI AGENT PERMISSIONS
-- ============================================

CREATE TABLE IF NOT EXISTS ai_agent_permissions (
    id TEXT PRIMARY KEY,
    property_id TEXT REFERENCES properties(id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    can_view_reservations INTEGER DEFAULT 1,
    can_create_reservations INTEGER DEFAULT 1,
    can_modify_reservations INTEGER DEFAULT 0,
    can_cancel_reservations INTEGER DEFAULT 0,
    can_view_guests INTEGER DEFAULT 1,
    can_modify_guests INTEGER DEFAULT 0,
    can_view_rooms INTEGER DEFAULT 1,
    can_modify_rooms INTEGER DEFAULT 0,
    can_modify_room_status INTEGER DEFAULT 0,
    can_view_prices INTEGER DEFAULT 1,
    can_modify_prices INTEGER DEFAULT 0,
    can_view_reports INTEGER DEFAULT 1,
    can_export_data INTEGER DEFAULT 0,
    can_modify_settings INTEGER DEFAULT 0,
    requires_confirmation INTEGER DEFAULT 1,  -- If TRUE, AI suggests but doesn't execute
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(property_id, role)
);

-- ============================================
-- MIGRATION TRACKING
-- ============================================

CREATE TABLE IF NOT EXISTS migration_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    version TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    applied_by TEXT DEFAULT 'system',
    success INTEGER DEFAULT 1,
    rollback_sql TEXT,
    UNIQUE(version, name)
);

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_rooms_property ON rooms_new(property_id);
CREATE INDEX IF NOT EXISTS idx_rooms_category ON rooms_new(category_id);
CREATE INDEX IF NOT EXISTS idx_rooms_status ON rooms_new(status);
CREATE INDEX IF NOT EXISTS idx_room_categories_property ON room_categories(property_id);
CREATE INDEX IF NOT EXISTS idx_client_types_property ON client_types(property_id);
CREATE INDEX IF NOT EXISTS idx_client_contracts_property ON client_contracts(property_id);
CREATE INDEX IF NOT EXISTS idx_client_contracts_type ON client_contracts(client_type_id);
CREATE INDEX IF NOT EXISTS idx_pricing_seasons_property ON pricing_seasons(property_id);
CREATE INDEX IF NOT EXISTS idx_pricing_seasons_dates ON pricing_seasons(start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_price_calculations_reservation ON price_calculations(reservation_id);
CREATE INDEX IF NOT EXISTS idx_room_status_log_room ON room_status_log(room_id);
CREATE INDEX IF NOT EXISTS idx_room_status_log_date ON room_status_log(changed_at);
"""

# SQL to alter existing reservations table
SQL_ALTER_RESERVATIONS = """
-- Add new columns to reservations table if they don't exist
-- SQLite doesn't support IF NOT EXISTS for ALTER TABLE, so we check in Python
ALTER TABLE reservations ADD COLUMN property_id TEXT;
ALTER TABLE reservations ADD COLUMN category_id TEXT;
ALTER TABLE reservations ADD COLUMN client_type_id TEXT;
ALTER TABLE reservations ADD COLUMN contract_id TEXT;
ALTER TABLE reservations ADD COLUMN price_breakdown TEXT;
ALTER TABLE reservations ADD COLUMN season_applied TEXT;
ALTER TABLE reservations ADD COLUMN original_price DECIMAL(12,2);
ALTER TABLE reservations ADD COLUMN discount_amount DECIMAL(12,2);
ALTER TABLE reservations ADD COLUMN final_price DECIMAL(12,2);
"""

# ============================================
# MIGRATION FUNCTIONS
# ============================================

def check_table_exists(conn: sqlite3.Connection, table_name: str) -> bool:
    """Check if a table exists in the database."""
    cursor = conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name=?",
        (table_name,)
    )
    return cursor.fetchone() is not None

def check_column_exists(conn: sqlite3.Connection, table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table."""
    cursor = conn.execute(f"PRAGMA table_info({table_name})")
    columns = [row[1] for row in cursor.fetchall()]
    return column_name in columns

def check_migration_applied(conn: sqlite3.Connection, version: str, name: str) -> bool:
    """Check if a migration has already been applied."""
    if not check_table_exists(conn, 'migration_history'):
        return False
    
    cursor = conn.execute(
        "SELECT id FROM migration_history WHERE version = ? AND name = ? AND success = 1",
        (version, name)
    )
    return cursor.fetchone() is not None

def record_migration(conn: sqlite3.Connection, version: str, name: str, description: str):
    """Record a successful migration."""
    conn.execute(
        """INSERT INTO migration_history (version, name, description, applied_by)
           VALUES (?, ?, ?, ?)""",
        (version, name, description, 'migrate_monges.py')
    )

def migrate_rooms_table(conn: sqlite3.Connection, dry_run: bool = False):
    """
    Migrate existing rooms table to new schema.
    - Preserves existing room data
    - Adds new columns for category support
    """
    log_info("Checking rooms table migration...")
    
    if not check_table_exists(conn, 'rooms'):
        log_info("No existing rooms table found. Will create new structure.")
        return
    
    # Check if already migrated (has property_id column)
    if check_column_exists(conn, 'rooms', 'property_id'):
        log_info("Rooms table already has new schema. Skipping migration.")
        return
    
    log_info("Migrating existing rooms table...")
    
    if dry_run:
        log_info("[DRY RUN] Would migrate rooms table to new schema")
        return
    
    # Get existing room data
    cursor = conn.execute("SELECT id, type, status FROM rooms")
    existing_rooms = cursor.fetchall()
    log_info(f"Found {len(existing_rooms)} existing rooms to preserve")
    
    # Rename old table
    conn.execute("ALTER TABLE rooms RENAME TO rooms_old")
    
    # Create new table (already in SQL_CREATE_TABLES as rooms_new)
    # We'll rename rooms_new to rooms after creation
    
    # Note: The actual data migration will be done in seed script
    # because we need property_id and category_id which don't exist yet
    
    log_success("Rooms table schema updated. Old data preserved in rooms_old.")

def add_properties_social_columns(conn: sqlite3.Connection, dry_run: bool = False):
    """Add social media columns to properties table."""
    log_info("Checking properties table for social media columns...")

    if not check_table_exists(conn, 'properties'):
        log_info("Properties table not found. Will be created with new schema.")
        return

    new_columns = [
        ('facebook_url', 'TEXT'),
        ('instagram_url', 'TEXT'),
    ]

    for column_name, column_type in new_columns:
        if check_column_exists(conn, 'properties', column_name):
            log_info(f"Column '{column_name}' already exists. Skipping.")
            continue

        if dry_run:
            log_info(f"[DRY RUN] Would add column: {column_name} {column_type}")
        else:
            try:
                conn.execute(f"ALTER TABLE properties ADD COLUMN {column_name} {column_type}")
                log_success(f"Added column: {column_name}")
            except sqlite3.OperationalError as e:
                if "duplicate column name" in str(e).lower():
                    log_info(f"Column '{column_name}' already exists.")
                else:
                    raise

def add_reservations_columns(conn: sqlite3.Connection, dry_run: bool = False):
    """Add new columns to reservations table for pricing support."""
    log_info("Checking reservations table...")
    
    if not check_table_exists(conn, 'reservations'):
        log_warning("Reservations table not found. Skipping column additions.")
        return
    
    new_columns = [
        ('property_id', 'TEXT'),
        ('category_id', 'TEXT'),
        ('client_type_id', 'TEXT'),
        ('contract_id', 'TEXT'),
        ('price_breakdown', 'TEXT'),
        ('season_applied', 'TEXT'),
        ('original_price', 'DECIMAL(12,2)'),
        ('discount_amount', 'DECIMAL(12,2)'),
        ('final_price', 'DECIMAL(12,2)'),
    ]
    
    for column_name, column_type in new_columns:
        if check_column_exists(conn, 'reservations', column_name):
            log_info(f"Column '{column_name}' already exists. Skipping.")
            continue
        
        if dry_run:
            log_info(f"[DRY RUN] Would add column: {column_name} {column_type}")
        else:
            try:
                conn.execute(f"ALTER TABLE reservations ADD COLUMN {column_name} {column_type}")
                log_success(f"Added column: {column_name}")
            except sqlite3.OperationalError as e:
                if "duplicate column name" in str(e).lower():
                    log_info(f"Column '{column_name}' already exists.")
                else:
                    raise

def run_migration(db_path: Path, dry_run: bool = False) -> bool:
    """
    Execute the full migration.
    
    Returns:
        True if migration was successful, False otherwise
    """
    log_section(f"DATABASE MIGRATION: {MIGRATION_NAME} v{MIGRATION_VERSION}")
    
    # Check database exists
    if not db_path.exists():
        log_error(f"Database not found: {db_path}")
        log_info("Please run the application first to create the initial database.")
        return False
    
    log_info(f"Database: {db_path}")
    log_info(f"Dry run: {dry_run}")
    
    # Connect to database
    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA foreign_keys = ON")
    
    try:
        # Check if migration already applied
        if check_migration_applied(conn, MIGRATION_VERSION, MIGRATION_NAME):
            log_warning(f"Migration {MIGRATION_NAME} v{MIGRATION_VERSION} already applied.")
            log_info("Use --force to re-run (not recommended).")
            return True
        
        # Start transaction
        if not dry_run:
            conn.execute("BEGIN TRANSACTION")
        
        # Step 1: Create new tables
        log_section("STEP 1: Creating New Tables")
        
        if dry_run:
            log_info("[DRY RUN] Would create the following tables:")
            tables = [
                'properties', 'buildings', 'room_categories', 'system_settings',
                'rooms_new', 'room_status_log', 'client_types', 'client_contracts',
                'pricing_seasons', 'price_calculations', 'ai_agent_permissions',
                'migration_history'
            ]
            for t in tables:
                exists = check_table_exists(conn, t)
                status = "EXISTS" if exists else "NEW"
                log_info(f"  - {t}: {status}")
        else:
            conn.executescript(SQL_CREATE_TABLES)
            log_success("New tables created successfully")
        
        # Step 2: Migrate rooms table
        log_section("STEP 2: Migrating Rooms Table")
        migrate_rooms_table(conn, dry_run)
        
        # Step 3: Add columns to reservations
        log_section("STEP 3: Updating Reservations Table")
        add_reservations_columns(conn, dry_run)

        # Step 3.5: Add social media columns to properties
        log_section("STEP 3.5: Adding Social Media Columns to Properties")
        add_properties_social_columns(conn, dry_run)

        # Step 4: Rename rooms_new to rooms (if rooms was migrated)
        log_section("STEP 4: Finalizing Room Structure")
        if check_table_exists(conn, 'rooms_new') and not check_table_exists(conn, 'rooms'):
            if dry_run:
                log_info("[DRY RUN] Would rename rooms_new to rooms")
            else:
                conn.execute("ALTER TABLE rooms_new RENAME TO rooms")
                log_success("Renamed rooms_new to rooms")
        elif check_table_exists(conn, 'rooms_new'):
            log_info("Both rooms and rooms_new exist. Manual review needed.")
        else:
            log_info("Room table structure already finalized.")
        
        # Step 5: Record migration
        log_section("STEP 5: Recording Migration")
        if not dry_run:
            record_migration(
                conn, 
                MIGRATION_VERSION, 
                MIGRATION_NAME,
                "Los Monges MVP: Added properties, categories, pricing, client types"
            )
            conn.execute("COMMIT")
            log_success("Migration recorded and committed")
        else:
            log_info("[DRY RUN] Would record migration in history")
        
        # Summary
        log_section("MIGRATION COMPLETE")
        
        if dry_run:
            log_warning("This was a DRY RUN. No changes were made.")
            log_info("Run without --dry-run to apply changes.")
        else:
            log_success(f"Migration {MIGRATION_NAME} v{MIGRATION_VERSION} applied successfully!")
            log_info("")
            log_info("Next steps:")
            log_info("  1. Run seed_monges.py to insert initial data")
            log_info("  2. Test the application")
            log_info("  3. If issues, restore from backup in /backups/")
        
        return True
        
    except Exception as e:
        log_error(f"Migration failed: {e}")
        if not dry_run:
            log_info("Rolling back changes...")
            conn.execute("ROLLBACK")
        raise
        
    finally:
        conn.close()

# ============================================
# MAIN ENTRY POINT
# ============================================

def main():
    """Main entry point for the migration script."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Migrate database for Los Monges MVP",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python migrate_monges.py              # Run migration with backup
  python migrate_monges.py --dry-run    # Show what would be done
  python migrate_monges.py --no-backup  # Skip backup (not recommended)
        """
    )
    parser.add_argument(
        '--dry-run', 
        action='store_true',
        help='Show what would be done without making changes'
    )
    parser.add_argument(
        '--no-backup',
        action='store_true',
        help='Skip automatic backup (not recommended)'
    )
    parser.add_argument(
        '--db-path',
        type=str,
        help='Custom database path (default: backend/hotel.db)'
    )
    
    args = parser.parse_args()
    
    # Determine database path
    db_path = Path(args.db_path) if args.db_path else DB_PATH
    
    print("")
    print("╔══════════════════════════════════════════════════════════╗")
    print("║     HOTEL MANAGEMENT SYSTEM - DATABASE MIGRATION         ║")
    print("║                  Los Monges MVP                          ║")
    print("╚══════════════════════════════════════════════════════════╝")
    print("")
    
    # Create backup unless skipped or dry run
    if not args.no_backup and not args.dry_run:
        try:
            log_section("PRE-MIGRATION BACKUP")
            backup_path = create_backup(db_path, BACKUP_DIR)
            log_info(f"Backup location: {backup_path}")
        except Exception as e:
            log_error(f"Backup failed: {e}")
            log_error("Aborting migration. Fix backup issue or use --no-backup (not recommended)")
            sys.exit(1)
    elif args.dry_run:
        log_info("Dry run mode - skipping backup")
    else:
        log_warning("Backup skipped by user request. Proceeding without backup.")
    
    # Run migration
    try:
        success = run_migration(db_path, dry_run=args.dry_run)
        sys.exit(0 if success else 1)
    except Exception as e:
        log_error(f"Migration failed with error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
