#!/usr/bin/env python3
"""
Hotel Management System - Seed Data Script
===========================================
seed_monges.py

This script inserts initial data for "Hospedaje Los Monges":
- Property configuration
- Room categories (6 types)
- Rooms (15 total)
- Default client types
- Default pricing seasons
- AI agent permissions
- System settings

USAGE:
    python scripts/seed_monges.py [--dry-run] [--reset]

FLAGS:
    --dry-run    Show what would be done without making changes
    --reset      Clear existing Los Monges data before seeding (DANGEROUS)

SAFETY:
    - Checks if data already exists before inserting
    - Safe to run multiple times (idempotent)
    - Use --reset only if you want to start fresh

Author: Generated by Claude Desktop
Date: 2026-01-31
Phase: Los Monges MVP
"""

import os
import sys
import sqlite3
import json
from datetime import datetime, date
from pathlib import Path
from uuid import uuid4

# ============================================
# CONFIGURATION
# ============================================

SCRIPT_DIR = Path(os.path.abspath(os.path.dirname(__file__)))
PROJECT_ROOT = SCRIPT_DIR.parent
BACKEND_DIR = PROJECT_ROOT / "backend"
DB_PATH = BACKEND_DIR / "hotel.db"

# Los Monges Property ID (fixed for consistency)
PROPERTY_ID = "los-monges"
PROPERTY_NAME = "Hospedaje Los Monges"

# ============================================
# LOGGING
# ============================================

def log_info(msg: str):
    print(f"[INFO] {msg}")

def log_success(msg: str):
    print(f"[✅] {msg}")

def log_warning(msg: str):
    print(f"[⚠️] {msg}")

def log_error(msg: str):
    print(f"[❌] {msg}")

def log_section(title: str):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}\n")

# ============================================
# SEED DATA DEFINITIONS
# ============================================

# Property configuration
PROPERTY_DATA = {
    "id": PROPERTY_ID,
    "name": PROPERTY_NAME,
    "slug": "los-monges",
    "display_mode": "category",  # Category-based, no visible room numbers
    "theme_background": "#FFFFFF",
    "theme_text": "#000000",
    "theme_primary": "#1E3A5F",
    "check_in_start": "07:00",
    "check_in_end": "22:00",
    "check_out_time": "10:00",
    "breakfast_included": 0,
    "parking_available": 1,
    "timezone": "America/Asuncion",
    "currency": "PYG",
    "address": "Calle Principal 123, Ciudad del Este, Paraguay",
    "phone": "+595 900 000000",
    "email": "contacto@hospedajelosmonges.com.py",
    "facebook_url": "https://www.facebook.com/losmonges",
    "instagram_url": "https://www.instagram.com/losmonges",
    "active": 1
}

# Building (single building for Los Monges)
BUILDING_DATA = {
    "id": f"{PROPERTY_ID}-principal",
    "property_id": PROPERTY_ID,
    "name": "Edificio Principal",
    "floors": 2,
    "description": "Edificio principal del hospedaje",
    "sort_order": 0,
    "active": 1
}

# Room categories with pricing
# NOTE: Quantities (qty) are estimates - update based on actual inventory
ROOM_CATEGORIES = [
    {
        "id": f"{PROPERTY_ID}-familiar",
        "name": "Departamento Familiar",
        "description": "2 habitaciones, ideal para familias grandes. Incluye 4 camas.",
        "base_price": 400000,  # 400,000 Gs per night
        "max_capacity": 6,
        "bed_configuration": json.dumps([
            {"type": "matrimonial", "qty": 1},
            {"type": "individual", "qty": 2},
            {"type": "litera", "qty": 1}
        ]),
        "amenities": json.dumps(["wifi", "ac", "tv", "frigobar", "baño_privado"]),
        "sort_order": 1,
        "qty": 2  # Estimated quantity - UPDATE THIS
    },
    {
        "id": f"{PROPERTY_ID}-familiar2",
        "name": "Departamento Familiar 2",
        "description": "2 ambientes con cama matrimonial y litera. Perfecto para familia de 4.",
        "base_price": 250000,  # 250,000 Gs per night
        "max_capacity": 4,
        "bed_configuration": json.dumps([
            {"type": "matrimonial", "qty": 1},
            {"type": "litera", "qty": 1}
        ]),
        "amenities": json.dumps(["wifi", "ac", "tv", "baño_privado"]),
        "sort_order": 2,
        "qty": 3  # Estimated quantity - UPDATE THIS
    },
    {
        "id": f"{PROPERTY_ID}-ejecutivo",
        "name": "Departamento Ejecutivo",
        "description": "3 ambientes amplios con 3 camas. Ideal para viajes de negocios en grupo.",
        "base_price": 300000,  # 300,000 Gs per night
        "max_capacity": 4,
        "bed_configuration": json.dumps([
            {"type": "matrimonial", "qty": 1},
            {"type": "individual", "qty": 2}
        ]),
        "amenities": json.dumps(["wifi", "ac", "tv", "frigobar", "escritorio", "baño_privado"]),
        "sort_order": 3,
        "qty": 2  # Estimated quantity - UPDATE THIS
    },
    {
        "id": f"{PROPERTY_ID}-doble",
        "name": "Departamento Doble",
        "description": "2 ambientes cómodos con 2 camas. Para parejas o amigos.",
        "base_price": 200000,  # 200,000 Gs per night
        "max_capacity": 3,
        "bed_configuration": json.dumps([
            {"type": "matrimonial", "qty": 1},
            {"type": "individual", "qty": 1}
        ]),
        "amenities": json.dumps(["wifi", "ac", "tv", "baño_privado"]),
        "sort_order": 4,
        "qty": 3  # Estimated quantity - UPDATE THIS
    },
    {
        "id": f"{PROPERTY_ID}-superior",
        "name": "Departamento Superior",
        "description": "2 ambientes con cama matrimonial. Confort superior para parejas.",
        "base_price": 200000,  # 200,000 Gs per night
        "max_capacity": 2,
        "bed_configuration": json.dumps([
            {"type": "matrimonial", "qty": 1}
        ]),
        "amenities": json.dumps(["wifi", "ac", "tv", "frigobar", "baño_privado"]),
        "sort_order": 5,
        "qty": 2  # Estimated quantity - UPDATE THIS
    },
    {
        "id": f"{PROPERTY_ID}-estandar",
        "name": "Departamento Estándar",
        "description": "Monoambiente acogedor con cama matrimonial. Económico y cómodo.",
        "base_price": 150000,  # 150,000 Gs per night
        "max_capacity": 2,
        "bed_configuration": json.dumps([
            {"type": "matrimonial", "qty": 1}
        ]),
        "amenities": json.dumps(["wifi", "ac", "tv", "baño_privado"]),
        "sort_order": 6,
        "qty": 3  # Estimated quantity - UPDATE THIS
    },
]

# Client types with discounts
CLIENT_TYPES = [
    {
        "id": f"{PROPERTY_ID}-particular",
        "name": "Particular",
        "description": "Huésped individual o familiar sin convenio",
        "default_discount_percent": 0,
        "requires_contract": 0,
        "min_rooms_per_booking": 1,
        "color": "#6B7280",  # Gray
        "icon": "user",
        "sort_order": 1
    },
    {
        "id": f"{PROPERTY_ID}-empresa",
        "name": "Empresa",
        "description": "Empresa con convenio corporativo",
        "default_discount_percent": 15,
        "requires_contract": 1,
        "min_rooms_per_booking": 1,
        "color": "#3B82F6",  # Blue
        "icon": "building",
        "sort_order": 2
    },
    {
        "id": f"{PROPERTY_ID}-grupo",
        "name": "Grupo",
        "description": "Reserva grupal (3+ habitaciones)",
        "default_discount_percent": 10,
        "requires_contract": 0,
        "min_rooms_per_booking": 3,
        "color": "#8B5CF6",  # Purple
        "icon": "users",
        "sort_order": 3
    },
    {
        "id": f"{PROPERTY_ID}-agencia",
        "name": "Agencia",
        "description": "Agencia de viajes con convenio",
        "default_discount_percent": 20,
        "requires_contract": 1,
        "min_rooms_per_booking": 1,
        "color": "#10B981",  # Green
        "icon": "globe",
        "sort_order": 4
    },
    {
        "id": f"{PROPERTY_ID}-booking",
        "name": "Booking.com",
        "description": "Reserva vía Booking.com (OTA tracking)",
        "default_discount_percent": 0,
        "requires_contract": 0,
        "min_rooms_per_booking": 1,
        "color": "#003580",  # Booking blue
        "icon": "calendar",
        "sort_order": 5
    },
    {
        "id": f"{PROPERTY_ID}-airbnb",
        "name": "Airbnb",
        "description": "Reserva vía Airbnb (OTA tracking)",
        "default_discount_percent": 0,
        "requires_contract": 0,
        "min_rooms_per_booking": 1,
        "color": "#FF5A5F",  # Airbnb red
        "icon": "home",
        "sort_order": 6
    },
    {
        "id": f"{PROPERTY_ID}-vip",
        "name": "VIP / Frecuente",
        "description": "Huésped frecuente o VIP con descuento especial",
        "default_discount_percent": 10,
        "requires_contract": 0,
        "min_rooms_per_booking": 1,
        "color": "#F59E0B",  # Amber/Gold
        "icon": "star",
        "sort_order": 7
    },
]

# Pricing seasons (examples - adjust dates as needed)
# Using 2026 as the base year
PRICING_SEASONS = [
    {
        "id": f"{PROPERTY_ID}-normal-2026",
        "name": "Temporada Normal",
        "description": "Tarifa estándar",
        "start_date": "2026-01-01",
        "end_date": "2026-12-31",
        "price_modifier": 1.0,  # Base price
        "priority": 0,  # Lowest priority (default)
        "color": "#6B7280",
        "active": 1
    },
    {
        "id": f"{PROPERTY_ID}-semanasanta-2026",
        "name": "Semana Santa 2026",
        "description": "Temporada alta - Semana Santa",
        "start_date": "2026-03-29",  # Approximate - adjust for actual dates
        "end_date": "2026-04-05",
        "price_modifier": 1.30,  # +30%
        "priority": 10,
        "color": "#EF4444",
        "active": 1
    },
    {
        "id": f"{PROPERTY_ID}-julio-2026",
        "name": "Vacaciones de Julio",
        "description": "Temporada alta - Vacaciones de invierno",
        "start_date": "2026-07-01",
        "end_date": "2026-07-31",
        "price_modifier": 1.20,  # +20%
        "priority": 5,
        "color": "#F59E0B",
        "active": 1
    },
    {
        "id": f"{PROPERTY_ID}-findeano-2026",
        "name": "Fin de Año 2026",
        "description": "Temporada alta - Navidad y Año Nuevo",
        "start_date": "2026-12-20",
        "end_date": "2027-01-05",
        "price_modifier": 1.40,  # +40%
        "priority": 10,
        "color": "#EF4444",
        "active": 1
    },
    {
        "id": f"{PROPERTY_ID}-baja-feb-2026",
        "name": "Temporada Baja Febrero",
        "description": "Temporada baja - Febrero",
        "start_date": "2026-02-01",
        "end_date": "2026-02-28",
        "price_modifier": 0.90,  # -10%
        "priority": 3,
        "color": "#10B981",
        "active": 1
    },
]

# AI Agent permissions by role
AI_PERMISSIONS = [
    {
        "id": f"{PROPERTY_ID}-admin",
        "role": "admin",
        "can_view_reservations": 1,
        "can_create_reservations": 1,
        "can_modify_reservations": 1,
        "can_cancel_reservations": 1,
        "can_view_guests": 1,
        "can_modify_guests": 1,
        "can_view_rooms": 1,
        "can_modify_rooms": 1,
        "can_modify_room_status": 1,
        "can_view_prices": 1,
        "can_modify_prices": 1,
        "can_view_reports": 1,
        "can_export_data": 1,
        "can_modify_settings": 1,
        "requires_confirmation": 0  # Admin can execute directly
    },
    {
        "id": f"{PROPERTY_ID}-supervisor",
        "role": "supervisor",
        "can_view_reservations": 1,
        "can_create_reservations": 1,
        "can_modify_reservations": 1,
        "can_cancel_reservations": 1,
        "can_view_guests": 1,
        "can_modify_guests": 1,
        "can_view_rooms": 1,
        "can_modify_rooms": 0,
        "can_modify_room_status": 1,
        "can_view_prices": 1,
        "can_modify_prices": 0,
        "can_view_reports": 1,
        "can_export_data": 1,
        "can_modify_settings": 0,
        "requires_confirmation": 1  # Needs confirmation for sensitive ops
    },
    {
        "id": f"{PROPERTY_ID}-recepcion",
        "role": "recepcion",
        "can_view_reservations": 1,
        "can_create_reservations": 1,
        "can_modify_reservations": 0,  # Can only view, not modify
        "can_cancel_reservations": 0,
        "can_view_guests": 1,
        "can_modify_guests": 1,
        "can_view_rooms": 1,
        "can_modify_rooms": 0,
        "can_modify_room_status": 1,  # Can mark as cleaning, etc.
        "can_view_prices": 1,
        "can_modify_prices": 0,
        "can_view_reports": 0,
        "can_export_data": 0,
        "can_modify_settings": 0,
        "requires_confirmation": 1
    },
]

# System settings
SYSTEM_SETTINGS = [
    {
        "setting_key": "hotel_name",
        "setting_value": PROPERTY_NAME,
        "setting_type": "string",
        "description": "Nombre del hotel para mostrar en la interfaz"
    },
    {
        "setting_key": "default_client_type",
        "setting_value": f"{PROPERTY_ID}-particular",
        "setting_type": "string",
        "description": "Tipo de cliente por defecto para nuevas reservas"
    },
    {
        "setting_key": "grupo_min_rooms",
        "setting_value": "3",
        "setting_type": "number",
        "description": "Mínimo de habitaciones para aplicar tarifa de grupo"
    },
    {
        "setting_key": "allow_overbooking",
        "setting_value": "false",
        "setting_type": "boolean",
        "description": "Permitir reservas aunque no haya disponibilidad"
    },
    {
        "setting_key": "reservation_requires_payment",
        "setting_value": "false",
        "setting_type": "boolean",
        "description": "Requerir pago/seña para confirmar reserva"
    },
    {
        "setting_key": "checkin_requires_document",
        "setting_value": "true",
        "setting_type": "boolean",
        "description": "Requerir documento de identidad para check-in"
    },
    {
        "setting_key": "ai_assistant_name",
        "setting_value": "Asistente Los Monges",
        "setting_type": "string",
        "description": "Nombre del asistente de IA"
    },
    {
        "setting_key": "ai_assistant_greeting",
        "setting_value": "¡Hola! Soy el asistente virtual de Hospedaje Los Monges. ¿En qué puedo ayudarte hoy?",
        "setting_type": "string",
        "description": "Saludo inicial del asistente de IA"
    },
]

# ============================================
# SEED FUNCTIONS
# ============================================

def check_data_exists(conn: sqlite3.Connection, table: str, id_column: str, id_value: str) -> bool:
    """Check if a record already exists."""
    cursor = conn.execute(f"SELECT 1 FROM {table} WHERE {id_column} = ?", (id_value,))
    return cursor.fetchone() is not None

def seed_property(conn: sqlite3.Connection, dry_run: bool = False):
    """Seed the property (hotel) record."""
    log_info(f"Seeding property: {PROPERTY_NAME}")
    
    if check_data_exists(conn, 'properties', 'id', PROPERTY_ID):
        log_warning(f"Property '{PROPERTY_ID}' already exists. Skipping.")
        return
    
    if dry_run:
        log_info(f"[DRY RUN] Would insert property: {PROPERTY_NAME}")
        return
    
    columns = ', '.join(PROPERTY_DATA.keys())
    placeholders = ', '.join(['?' for _ in PROPERTY_DATA])
    values = tuple(PROPERTY_DATA.values())
    
    conn.execute(f"INSERT INTO properties ({columns}) VALUES ({placeholders})", values)
    log_success(f"Property '{PROPERTY_NAME}' created")

def seed_building(conn: sqlite3.Connection, dry_run: bool = False):
    """Seed the building record."""
    log_info(f"Seeding building: {BUILDING_DATA['name']}")
    
    if check_data_exists(conn, 'buildings', 'id', BUILDING_DATA['id']):
        log_warning(f"Building '{BUILDING_DATA['id']}' already exists. Skipping.")
        return
    
    if dry_run:
        log_info(f"[DRY RUN] Would insert building: {BUILDING_DATA['name']}")
        return
    
    columns = ', '.join(BUILDING_DATA.keys())
    placeholders = ', '.join(['?' for _ in BUILDING_DATA])
    values = tuple(BUILDING_DATA.values())
    
    conn.execute(f"INSERT INTO buildings ({columns}) VALUES ({placeholders})", values)
    log_success(f"Building '{BUILDING_DATA['name']}' created")

def seed_categories(conn: sqlite3.Connection, dry_run: bool = False):
    """Seed room categories."""
    log_info(f"Seeding {len(ROOM_CATEGORIES)} room categories...")
    
    inserted = 0
    skipped = 0
    updated = 0
    
    for cat in ROOM_CATEGORIES:
        if check_data_exists(conn, 'room_categories', 'id', cat['id']):
            log_info(f"  Category '{cat['name']}' already exists. Updating...")
            
            # Remove 'qty' which is not a database column
            cat_data = {k: v for k, v in cat.items() if k != 'qty'}
            
            # Construct UPDATE statement
            set_clause = ', '.join([f"{k} = ?" for k in cat_data.keys()])
            values = tuple(cat_data.values()) + (cat['id'],)
            
            conn.execute(f"UPDATE room_categories SET {set_clause} WHERE id = ?", values)
            log_success(f"  Category '{cat['name']}' updated")
            updated += 1
            inserted += 1 # Count as processed
            continue
        
        if dry_run:
            log_info(f"  [DRY RUN] Would insert: {cat['name']} - {cat['base_price']:,} Gs")
            inserted += 1
            continue
        
        # Remove 'qty' which is not a database column
        cat_data = {k: v for k, v in cat.items() if k != 'qty'}
        cat_data['property_id'] = PROPERTY_ID
        
        columns = ', '.join(cat_data.keys())
        placeholders = ', '.join(['?' for _ in cat_data])
        values = tuple(cat_data.values())
        
        conn.execute(f"INSERT INTO room_categories ({columns}) VALUES ({placeholders})", values)
        log_success(f"  Category '{cat['name']}' created ({cat['base_price']:,} Gs)")
        inserted += 1
    
    log_info(f"Categories: {inserted} processed (created/updated), {skipped} skipped")

def seed_rooms(conn: sqlite3.Connection, dry_run: bool = False):
    """Seed individual rooms based on category quantities."""
    log_info("Seeding rooms...")
    
    total_rooms = sum(cat['qty'] for cat in ROOM_CATEGORIES)
    log_info(f"Total rooms to create: {total_rooms}")
    
    inserted = 0
    skipped = 0
    room_counter = 1
    
    for cat in ROOM_CATEGORIES:
        category_id = cat['id']
        qty = cat['qty']
        
        for i in range(1, qty + 1):
            # Generate internal code like "DF-01" for Departamento Familiar room 1
            prefix = ''.join(word[0].upper() for word in cat['name'].split()[:2])
            internal_code = f"{prefix}-{i:02d}"
            room_id = f"{PROPERTY_ID}-room-{room_counter:03d}"
            
            if check_data_exists(conn, 'rooms', 'id', room_id):
                log_info(f"  Room '{room_id}' already exists. Skipping.")
                skipped += 1
                room_counter += 1
                continue
            
            if dry_run:
                log_info(f"  [DRY RUN] Would insert: {internal_code} ({cat['name']})")
                inserted += 1
                room_counter += 1
                continue
            
            room_data = {
                'id': room_id,
                'property_id': PROPERTY_ID,
                'category_id': category_id,
                'floor': 1 if room_counter <= 8 else 2,  # Split between floors
                'internal_code': internal_code,
                'status': 'available',
                'active': 1
            }
            
            columns = ', '.join(room_data.keys())
            placeholders = ', '.join(['?' for _ in room_data])
            values = tuple(room_data.values())
            
            conn.execute(f"INSERT INTO rooms ({columns}) VALUES ({placeholders})", values)
            inserted += 1
            room_counter += 1
    
    log_success(f"Rooms: {inserted} inserted, {skipped} skipped")

def seed_client_types(conn: sqlite3.Connection, dry_run: bool = False):
    """Seed client types."""
    log_info(f"Seeding {len(CLIENT_TYPES)} client types...")
    
    inserted = 0
    skipped = 0
    
    for ct in CLIENT_TYPES:
        if check_data_exists(conn, 'client_types', 'id', ct['id']):
            log_info(f"  Client type '{ct['name']}' already exists. Skipping.")
            skipped += 1
            continue
        
        if dry_run:
            log_info(f"  [DRY RUN] Would insert: {ct['name']} ({ct['default_discount_percent']}% discount)")
            inserted += 1
            continue
        
        ct_data = {**ct, 'property_id': PROPERTY_ID}
        
        columns = ', '.join(ct_data.keys())
        placeholders = ', '.join(['?' for _ in ct_data])
        values = tuple(ct_data.values())
        
        conn.execute(f"INSERT INTO client_types ({columns}) VALUES ({placeholders})", values)
        log_success(f"  Client type '{ct['name']}' created ({ct['default_discount_percent']}% discount)")
        inserted += 1
    
    log_info(f"Client types: {inserted} inserted, {skipped} skipped")

def seed_pricing_seasons(conn: sqlite3.Connection, dry_run: bool = False):
    """Seed pricing seasons."""
    log_info(f"Seeding {len(PRICING_SEASONS)} pricing seasons...")
    
    inserted = 0
    skipped = 0
    
    for season in PRICING_SEASONS:
        if check_data_exists(conn, 'pricing_seasons', 'id', season['id']):
            log_info(f"  Season '{season['name']}' already exists. Skipping.")
            skipped += 1
            continue
        
        modifier_display = f"+{int((season['price_modifier']-1)*100)}%" if season['price_modifier'] > 1 else f"{int((season['price_modifier']-1)*100)}%"
        
        if dry_run:
            log_info(f"  [DRY RUN] Would insert: {season['name']} ({modifier_display})")
            inserted += 1
            continue
        
        season_data = {**season, 'property_id': PROPERTY_ID}
        
        columns = ', '.join(season_data.keys())
        placeholders = ', '.join(['?' for _ in season_data])
        values = tuple(season_data.values())
        
        conn.execute(f"INSERT INTO pricing_seasons ({columns}) VALUES ({placeholders})", values)
        log_success(f"  Season '{season['name']}' created ({modifier_display})")
        inserted += 1
    
    log_info(f"Seasons: {inserted} inserted, {skipped} skipped")

def seed_ai_permissions(conn: sqlite3.Connection, dry_run: bool = False):
    """Seed AI agent permissions."""
    log_info(f"Seeding {len(AI_PERMISSIONS)} AI permission sets...")
    
    inserted = 0
    skipped = 0
    
    for perm in AI_PERMISSIONS:
        if check_data_exists(conn, 'ai_agent_permissions', 'id', perm['id']):
            log_info(f"  Permissions for role '{perm['role']}' already exist. Skipping.")
            skipped += 1
            continue
        
        if dry_run:
            log_info(f"  [DRY RUN] Would insert permissions for: {perm['role']}")
            inserted += 1
            continue
        
        perm_data = {**perm, 'property_id': PROPERTY_ID}
        
        columns = ', '.join(perm_data.keys())
        placeholders = ', '.join(['?' for _ in perm_data])
        values = tuple(perm_data.values())
        
        conn.execute(f"INSERT INTO ai_agent_permissions ({columns}) VALUES ({placeholders})", values)
        log_success(f"  Permissions for '{perm['role']}' created")
        inserted += 1
    
    log_info(f"AI permissions: {inserted} inserted, {skipped} skipped")

def seed_system_settings(conn: sqlite3.Connection, dry_run: bool = False):
    """Seed system settings."""
    log_info(f"Seeding {len(SYSTEM_SETTINGS)} system settings...")
    
    inserted = 0
    skipped = 0
    updated = 0
    
    for setting in SYSTEM_SETTINGS:
        setting_id = f"{PROPERTY_ID}-{setting['setting_key']}"
        
        if check_data_exists(conn, 'system_settings', 'id', setting_id):
            log_info(f"  Setting '{setting['setting_key']}' already exists. Skipping.")
            skipped += 1
            continue
        
        if dry_run:
            log_info(f"  [DRY RUN] Would insert: {setting['setting_key']} = {setting['setting_value']}")
            inserted += 1
            continue
        
        setting_data = {
            'id': setting_id,
            'property_id': PROPERTY_ID,
            **setting
        }
        
        columns = ', '.join(setting_data.keys())
        placeholders = ', '.join(['?' for _ in setting_data])
        values = tuple(setting_data.values())
        
        conn.execute(f"INSERT INTO system_settings ({columns}) VALUES ({placeholders})", values)
        log_success(f"  Setting '{setting['setting_key']}' created")
        inserted += 1
    
    log_info(f"Settings: {inserted} inserted, {skipped} skipped")

def reset_los_monges_data(conn: sqlite3.Connection, dry_run: bool = False):
    """Remove all Los Monges data (use with caution!)."""
    log_warning("RESETTING ALL LOS MONGES DATA!")
    
    tables_to_clear = [
        ('system_settings', 'property_id'),
        ('ai_agent_permissions', 'property_id'),
        ('pricing_seasons', 'property_id'),
        ('client_contracts', 'property_id'),
        ('client_types', 'property_id'),
        ('rooms', 'property_id'),
        ('room_categories', 'property_id'),
        ('properties', 'id'),
    ]
    
    for table, column in tables_to_clear:
        if dry_run:
            log_info(f"[DRY RUN] Would delete from {table} WHERE {column} = '{PROPERTY_ID}'")
        else:
            try:
                cursor = conn.execute(f"DELETE FROM {table} WHERE {column} = ?", (PROPERTY_ID,))
                log_info(f"  Deleted {cursor.rowcount} rows from {table}")
            except sqlite3.OperationalError as e:
                log_warning(f"  Could not clear {table}: {e}")
    
    if not dry_run:
        log_success("Los Monges data reset complete")

# ============================================
# MAIN
# ============================================

def run_seed(db_path: Path, dry_run: bool = False, reset: bool = False) -> bool:
    """Execute the full seeding process."""
    log_section(f"SEEDING DATA: {PROPERTY_NAME}")
    
    if not db_path.exists():
        log_error(f"Database not found: {db_path}")
        log_info("Please run migrate_monges.py first.")
        return False
    
    log_info(f"Database: {db_path}")
    log_info(f"Dry run: {dry_run}")
    log_info(f"Reset: {reset}")
    
    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA foreign_keys = ON")
    
    try:
        # Start transaction
        if not dry_run:
            conn.execute("BEGIN TRANSACTION")
        
        # Reset if requested
        if reset:
            log_section("STEP 0: Reset Existing Data")
            reset_los_monges_data(conn, dry_run)
        
        # Seed in order (respecting foreign keys)
        log_section("STEP 1: Property")
        seed_property(conn, dry_run)
        
        # NOTE: buildings table removed from schema — skipping seed_building()

        log_section("STEP 2: Room Categories")
        seed_categories(conn, dry_run)
        
        log_section("STEP 3: Rooms")
        seed_rooms(conn, dry_run)

        log_section("STEP 4: Client Types")
        seed_client_types(conn, dry_run)

        log_section("STEP 5: Pricing Seasons")
        seed_pricing_seasons(conn, dry_run)

        log_section("STEP 6: AI Permissions")
        seed_ai_permissions(conn, dry_run)

        log_section("STEP 7: System Settings")
        seed_system_settings(conn, dry_run)
        
        # Commit
        if not dry_run:
            conn.execute("COMMIT")
        
        # Summary
        log_section("SEEDING COMPLETE")
        
        if dry_run:
            log_warning("This was a DRY RUN. No changes were made.")
            log_info("Run without --dry-run to apply changes.")
        else:
            log_success(f"Data for '{PROPERTY_NAME}' seeded successfully!")
            log_info("")
            log_info("Summary:")
            log_info(f"  - 1 property")
            log_info(f"  - {len(ROOM_CATEGORIES)} room categories")
            log_info(f"  - {sum(cat['qty'] for cat in ROOM_CATEGORIES)} rooms")
            log_info(f"  - {len(CLIENT_TYPES)} client types")
            log_info(f"  - {len(PRICING_SEASONS)} pricing seasons")
            log_info(f"  - {len(AI_PERMISSIONS)} AI permission sets")
            log_info(f"  - {len(SYSTEM_SETTINGS)} system settings")
            log_info("")
            log_info("Next steps:")
            log_info("  1. Update room quantities in this script if needed")
            log_info("  2. Run the application and test")
            log_info("  3. Add company contracts via the UI or another script")
        
        return True
        
    except Exception as e:
        log_error(f"Seeding failed: {e}")
        if not dry_run:
            log_info("Rolling back changes...")
            conn.execute("ROLLBACK")
        raise
        
    finally:
        conn.close()

def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Seed initial data for Los Monges",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python seed_monges.py              # Seed data
  python seed_monges.py --dry-run    # Show what would be done
  python seed_monges.py --reset      # Clear and re-seed (DANGEROUS)
        """
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Show what would be done without making changes'
    )
    parser.add_argument(
        '--reset',
        action='store_true',
        help='Clear existing Los Monges data before seeding (DANGEROUS)'
    )
    parser.add_argument(
        '--db-path',
        type=str,
        help='Custom database path (default: backend/hotel.db)'
    )
    
    args = parser.parse_args()
    
    db_path = Path(args.db_path) if args.db_path else DB_PATH
    
    print("")
    print("╔══════════════════════════════════════════════════════════╗")
    print("║     HOTEL MANAGEMENT SYSTEM - SEED DATA                  ║")
    print("║                  Los Monges MVP                          ║")
    print("╚══════════════════════════════════════════════════════════╝")
    print("")
    
    # Confirm reset
    if args.reset and not args.dry_run:
        log_warning("You are about to DELETE all Los Monges data and re-seed!")
        response = input("Type 'YES' to confirm: ")
        if response != 'YES':
            log_info("Aborted.")
            sys.exit(0)
    
    try:
        success = run_seed(db_path, dry_run=args.dry_run, reset=args.reset)
        sys.exit(0 if success else 1)
    except Exception as e:
        log_error(f"Seeding failed with error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
